apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app-container
          image: ${USER_ID}.dkr.ecr.us-east-1.amazonaws.com/node-js_app:${BUILD_NUMBER}
          ports:
          - containerPort: 3000

