apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-nodejs
  namespace: argo
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.app-svc.svc'
  project: default
  source: 
    path: kubernetes/nodejs-app/.
    repoURL: 'https://github.com/Badawi02/test.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
