apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-db-mongo
  namespace: argo
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  project: default
  source: 
    path: kubernetes/mongo-DB/.
    repoURL: 'https://github.com/Badawi02/test.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
